version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bat-grocy_web_1
      APP_PORT: 3010
    container_name: bat-grocy_app_proxy_1

  web:
    image: lscr.io/linuxserver/grocy:latest
    container_name: bat-grocy_web_1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST5EDT
    volumes:
      - ${APP_DATA_DIR}/config:/config
    restart: unless-stopped
