version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: bat-grocy_server_1
      APP_PORT: 80
    
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST5EDT
    volumes:
      - ${APP_DATA_DIR}/config:/config
    ports:
      - 9283:80
    restart: unless-stopped
