version: "3.7"

services:
    
  server:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST5EDT
    volumes:
      - ${APP_DATA_DIR}/config:/config
    ports:
      - 9283:80
    restart: unless-stopped
