version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bat-wishthis_web_1
      APP_PORT: 80
    container_name: bat-wishthis_app_proxy_1

  web:
    container_name: bat-wishthis_web_1
    restart: unless-stopped
    image: hiob/wishthis:stable
    volumes:
      - ${APP_DATA_DIR}/config.php:/var/www/html/src/config/config.php